/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window_princ;
  GtkWidget *window_gestion;
  GtkWidget *window_supp;
  GtkWidget *window_modif;
  GtkWidget *window_consul;
  GtkWidget *window_consul_cherch;
  GtkWidget *window_ajout;
  GtkWidget *window_cherch;
  GtkWidget *window_princ_espace_emp;
  GtkWidget *espaceclient;
  GtkWidget *window_auth_client;
  GtkWidget *fenetre_login;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window_princ = create_window_auth_admin ();
  gtk_widget_show (window_princ);
 /* window_princ_espace_emp = create_window_princ_espace_emp ();
  gtk_widget_show (window_princ_espace_emp);
  espaceclient = create_espace_client ();
  gtk_widget_show (espaceclient);*/
  /*window_gestion = create_window_gestion ();
  gtk_widget_show (window_gestion);
  window_supp = create_window_supp ();
  gtk_widget_show (window_supp);
  window_modif = create_window_modif ();
  gtk_widget_show (window_modif);
  window_consul = create_window_consul ();
  gtk_widget_show (window_consul);
  window_consul_cherch = create_window_consul_cherch ();
  gtk_widget_show (window_consul_cherch);
  window_ajout = create_window_ajout ();
  gtk_widget_show (window_ajout);
  window_cherch = create_window_cherch ();
  gtk_widget_show (window_cherch);*/
  window_auth_client = create_window_auth_client ();
  gtk_widget_show (window_auth_client);
  fenetre_login = create_fenetre_login ();
  gtk_widget_show (fenetre_login);


  gtk_main ();
  return 0;
}

